- name: set my.cnf location Debian
  set_fact:
    my_cnf: "/etc/mysql/my.cnf"
  when: ansible_distribution == "Debian" and ansible_distribution_version == "8.0"

- name: set my.cnf location Debian
  set_fact:
    my_cnf: "/etc/mysql/mariadb.conf.d/50-server.cnf"
  when: ansible_distribution == "Debian" and ansible_distribution_version == "9.0"


- name: set my.cnf location Ubuntu
  set_fact:
    my_cnf: "/etc/mysql/mysql.conf.d/mysqld.cnf"
  when: ansible_distribution == "Ubuntu" 
