# Allow http https access in ferm
- name: Allow apache IPv4 access in ferm
  become: yes
  copy:
    src: ferm-{{ item }}
    dest: /etc/ferm/ferm.d/{{ item }}
    owner: root
    group: root
    mode: 0640
  notify: Restart ferm
  with_items: 50-http-https
  tags: ferm
