# Add site and enable
- name: Configure site
  become: yes
  template:
    src: site.j2
    dest: "/etc/apache2/sites-available/{{ site.name }}.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes


- name: Enable site
  become: yes
  command: a2ensite {{ site.name }}
  notify:
    - Restart httpd

# Disable default sites
- name: Disable default sites
  become: yes
  command: a2dissite {{ item }}
  with_items:
   - 000-default
   - default-ssl
  notify:
    - Restart httpd
