---
- hosts: coturn-rest
  vars: 
    coturn_rest: true  
  roles:
    - { role: base }
    - { role: letsencrypt }
    - { role: mysql }
    - { role: mysql-replication }
    - { role: coturn }
    - { role: munin }
