---
- hosts: frontend
  roles:
    - { role: base }
    - { role: letsencrypt }
    - { role: mysql }
    - { role: mysql-replication }
    - { role: coturn }
    - { role: apache }
    - { role: geoip }
    - { role: php }
    - { role: ssp }
    - { role: composer }
    - { role: web }
    - { role: munin-master }
