# Setup /etc/hostname
- name: Setup hostname
  become: yes
  hostname:
    name: "{{ host.hostname }}"

# Setup /etc/hosts
- name: Setup hosts for 127.0.1.1
  become: yes
  lineinfile:
    backrefs: yes
    dest: /etc/hosts
    regexp: '^(127.0.1.1).*$'
    line: '\1	{{ host.hostname }}.{{ host.domain }} {{ host.hostname }}'
  notify: Restart networking

- name: Setup hosts ipv4
  become: yes
  lineinfile:
    dest: /etc/hosts
    insertafter: '^127.0.1.1	localhost$'
    line: '{{ ipv4.address }}	{{ host.hostname }}.{{ host.domain }} {{ host.hostname }}'
  notify: Restart networking


- name: Setup hosts ipv4
  become: yes
  lineinfile:
    dest: /etc/hosts
    insertafter: '^::1     localhost ip6-localhost ip6-loopback$'
    line: '{{ ipv6.address }}	{{ host.hostname }}.{{ host.domain }} {{ host.hostname }}'
  notify: Restart networking
