- name: Update resolv.conf if necessary
  become: yes
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  when: uncommon_resolvconf is undefined



