- name: Restart sshd
  become: yes
  service:
    name: ssh
    state: restarted

- name: Restart networking
  become: yes
  service:
    name: networking
    state: restarted

- name: Restart ferm
  become: yes
  service:
    name: ferm
    state: restarted

- name: update timezone
  become: yes
  command: dpkg-reconfigure --frontend noninteractive tzdata

