- name: Install mysql-server
  become: yes
  apt: 
    name: '{{ item }}'
    state: installed
    update_cache: yes
  with_items:
   - mysql-client
   - mysql-server
   - python-mysqldb
  notify: start mysql
