# Increase memory in php
- name: Increase memory in php
  become: yes
  lineinfile: 
    dest: /etc/php5/apache2/php.ini
    regexp: '^(memory_limit =) 128M$'
    line: '\1 512M'
    state: present
    backrefs: yes
  notify:
    - Restart httpd

# Increase execution time in php
- name: Increase execution time in php
  become: yes
  lineinfile: 
    dest: /etc/php5/apache2/php.ini
    regexp: '^(max_execution_time =) 30$'
    line: '\1 120'
    state: present
    backrefs: yes
  notify:
    - Restart httpd
 
