# Update interfaces

- name: Setup networking in etc interfaces
  become: yes
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
  when: uncommon_interfaces is undefined
  notify: Restart networking


