- name: last prompt before reboot
  pause: 
    prompt: "Make a last config check before reboot!!! \nPress any key to reboot or \"<ctrl>-c a\" to abbort!!! "
  tags: test
 
- name: restart machine
  shell: sleep 2 && shutdown -r now "After basic setup ansible reboot triggered"
  async: 1
  poll: 0
  become: yes
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ host.hostname }}.{{ host.domain }} state=started delay=30 timeout=300
  become: no

