# install munin-node
- name: Install munin-node package
  become: yes
  apt: 
    name: munin-node 
    state: installed
    update_cache: yes

- name: Setup munin-master allowed munin-master ipv4
  become: yes
  lineinfile: 
    dest: /etc/munin/munin-node.conf
    line: 'allow {{ munin_master_ipv4_regex }}'
    insertafter: 'allow ^127\.0\.0\.1$'
    state: present
  notify: Restart munin-node

- name: Setup munin-master allowed munin-master ipv6
  become: yes
  lineinfile: 
    dest: /etc/munin/munin-node.conf
    line: 'allow {{ munin_master_ipv6_regex }}'
    insertafter: 'allow ^::1$'
    state: present
  notify: Restart munin-node

- name: Allow munin port from munin-master in ferm
  become: yes
  template: 
    src: ferm-{{ item }}.j2
    dest: /etc/ferm/ferm.d/{{ item }}
    owner: root
    group: root
    mode: 0640
  notify: Restart ferm
  with_items:
    - 55-munin-master
  tags: ferm

- name: insert client into munin-master config 
  become: yes
  lineinfile:
    dest: /etc/munin/munin.conf
    line: "[{{ ansible_fqdn }}]\n    address {{ ansible_fqdn }}\n"
    insertafter: EOF
    state: present
  delegate_to: '{{ munin_master_fqdn }}'
