# install munin-node
- name: Install munin-node package
  become: yes
  apt: 
    name: munin-node 
    state: installed
    update_cache: yes

- name: Setup munin-master allowed munin-master ipv4
  become: yes
  lineinfile: 
    dest: /etc/munin/munin-node.conf
    line: 'allow {{ munin_master_ipv4_regex }}'
    insertafter: 'allow ^127\.0\.0\.1$'
    state: present
  notify: Restart munin-node

- name: Setup munin-master allowed munin-master ipv6
  become: yes
  lineinfile: 
    dest: /etc/munin/munin-node.conf
    line: 'allow {{ munin_master_ipv6_regex }}'
    insertafter: 'allow ^::1$'
    state: present
  notify: Restart munin-node

- name: Add allow munin port from munin-master on IPv4
  become: yes
  lineinfile:
    dest: /etc/ferm/ferm.conf
    line: "\n            # allow munin from connection\n            saddr {{ munin_master_fqdn }} proto tcp dport munin ACCEPT;\n"
    insertafter: '# Further IPv4 INPUT rules$'
    state: present
  notify: Reload ferm

- name: Add allow munin port from munin-master on IPv6
  become: yes
  lineinfile:
    dest: /etc/ferm/ferm.conf
    line: "\n            # allow munin from connection\n            saddr {{ munin_master_fqdn }} proto tcp dport munin ACCEPT;\n"
    insertafter: '# Further IPv6 INPUT rules$'
    state: present
  notify: Reload ferm


- name: insert client into munin-master config 
  become: yes
  lineinfile:
    dest: /etc/munin/munin.conf
    line: "[{{ ansible_fqdn }}]\n    address {{ ansible_fqdn }}\n"
    insertafter: EOF
    state: present
  delegate_to: '{{ munin_master_fqdn }}'
