# Setup mysql server id for master and slave
- name: Setup mysql server id 
  become: yes
  lineinfile: 
    dest: /etc/mysql/my.cnf 
    regexp: '^#(server-id		=) 1$'
    line: '\1 {{ mysql_server_id }}'
    backrefs: yes
    state: present
  notify: Restart mysql
