# coturn ferm

- name: Add coturn rules to ferm firewall config
  become: yes
  copy: 
    src: ferm-{{ item }}
    dest: /etc/ferm/ferm.d/{{ item }}
    owner: root
    group: root
    mode: 0640
  notify: Restart ferm
  with_items: 52-coturn
  tags: ferm
