- import_tasks: mysql-master.yml
  when: mysql_replication_role == "master"
- import_tasks: package.yml
  when: mysql_replication_role == "slave"
- import_tasks: mysql-slave.yml
  when: mysql_replication_role == "slave"
- import_tasks: config.yml
  when: mysql_replication_role == "slave"
- import_tasks: ferm.yml
  when: mysql_replication_role == "slave"
- import_tasks: pki.yml
  when: mysql_replication_role == "slave"


