# coturn install

- name: Add Debian Jessie Backports
  become: yes
  apt_repository:
    repo: 'deb http://http.debian.net/debian jessie-backports main'
    state: present
  when: ansible_distribution == "Debian"

- name: Add Debian Jessie Backports Source
  become: yes
  apt_repository:
    repo: 'deb-src http://http.debian.net/debian jessie-backports main'
    state: present
    update_cache: yes
  when: ansible_distribution == "Debian"
  
- name: Install coturn package Debian
  become: yes
  apt:
    name: coturn
    default_release: jessie-backports 
    force: yes
    update_cache: yes
    state: latest
  when: ansible_distribution == "Debian"

- name: Install coturn package Ubuntu
  become: yes
  apt:
    name: coturn
    force: yes
    update_cache: yes
    state: latest
  when: ansible_distribution == "Ubuntu"
